version: 2

builds:
  - main: ./cmd/aidb
    binary: aidb
    ldflags:
      - -s -w -X github.com/KakkoiDev/aidb/cmd/aidb/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: KakkoiDev
    name: aidb
